"""
A generic setup.py file generated by django duke client 0.0.1
"""

from setuptools import setup, find_packages

setup(
    name = "django-userena-dev",
    version = "0.0.1",
    url = "",
    license = "",
    description = "",
    author = '',
    packages = find_packages('.duke/eggs/'),
    package_dir = {'': '.'},
    install_requires = [],
)
